Fix ReactJS TypeError, Issue #323
frappe/charts pull request #325
Opened 2021-01-13 20:11 UTC by raibtoffoletto

###### Explanation About What Code Achieves:

  - This fixes Issue #323 where ReactJS throws a TypeError.
  - It just adds a few IF assertions to easily correct the problem.

2021-03-10 07:44 UTC, scmmishra requested changes

2021-03-10 07:44 UTC, scmmishra commented on src/js/utils/animation.js
> +		if(parent) {
```suggestion
		if (parent) {
```

2021-03-10 07:44 UTC, scmmishra commented on src/js/utils/animation.js
> +		if(animElement[1]) {
```suggestion
		if (animElement[1]) {
```

2021-03-10 07:44 UTC, scmmishra approved these changes

2021-03-10 07:44 UTC, merged

2021-03-10 07:45 UTC, scmmishra commented
hey @raibtoffoletto thanks for the fix. Can you backport this to `v2-beta` branch?

2021-03-27 06:35 UTC, raibtoffoletto commented
Hi @scmmishra, sorry my delay in replying, I'm glad do help. Will create a pr for the v2-beta =D

(ps: I don't know why my JS formatter didn't take care of the spacing).

2021-03-27 06:49 UTC, raibtoffoletto commented
ps2: It seems it's already on the beta branch, thanks for that. Cheers